version: '3.7'
services:
    nagioscore:
        container_name: nagioscore
        build: 
            context: . 
            dockerfile: docker/Dockerfile 
        volumes:
         - .:/var/www/html
         - nagios-plugins-bin:/var/www/plugins
        ports:
         - "8080:80"
        depends_on:
         - apache
    plugins:
        container_name: nagios-plugins
        image: iwhite5/nagios-plugins:latest
        volumes:
         - nagios-plugins-bin:/var/www/plugins
        depends_on:
         - nagioscore
    apache:
        container_name: apache
        image: httpd:latest
volumes:
    nagios-plugins-bin:


